### ISSUE TITLE
挂载完成后服务未能找到speaker

### ISSUE THREAD

**Issue by AILANTEL** [Artrajz/MoeGoe-Simple-API#10]
挂载是成功的，但是无法查询到speaker
![image](https://user-images.githubusercontent.com/95335008/229866457-bb22f22c-1b3d-448d-ac23-5d1deae817e5.png)

**Comment by Artrajz** [comment]
可能是模型加载的问题，能提供配置文件吗？
话说你昨天不是加载成功了😧

**Comment by AILANTEL** [comment]
后来尝试不使用docker使用python直接创建就成功了，应该是镜像的问题。
