### ISSUE TITLE
部署成功，打不开HTTP请求

### ISSUE THREAD

**Issue by joe12801** [Artrajz/MoeGoe-Simple-API#13]
![image](https://user-images.githubusercontent.com/70465495/230321409-dae82e14-f58b-476f-813c-19935e574867.png)
![image](https://user-images.githubusercontent.com/70465495/230321508-4c485413-a927-4c28-a4ba-40d73611bf6f.png)
![image](https://user-images.githubusercontent.com/70465495/230321599-ef64183c-0e66-4a0f-b6c7-4df254d1be58.png)
![image](https://user-images.githubusercontent.com/70465495/230321967-9ebf2bd6-49ba-4785-a800-858ff9ef486c.png)

**Comment by Artrajz** [comment]
试试http://127.0.0.1:23456/voice/speakers
http://127.0.1:23456/voice/  结尾带/

**Comment by joe12801** [comment]
我用最新你的config.py 本机IP可以显示了 
![image](https://user-images.githubusercontent.com/70465495/230326873-6ea1c048-1769-4347-9872-d467f6149c8b.png)
但是在公网IP在还是没作用，打不开 
![image](https://user-images.githubusercontent.com/70465495/230327250-73506a52-0da8-4574-b32a-326ea5bde15c.png)

**Comment by Artrajz** [comment]
你发的两张图中顶级域名都不一样，请再检查一下

**Comment by joe12801** [comment]
![image](https://user-images.githubusercontent.com/70465495/230333415-c5f2b149-7036-48d3-8960-1b2d6711d355.png)
一样打不开，不知道什么情况

**Comment by Artrajz** [comment]
请再次注意，http://127.0.0.1:23456/voice是错误的写法，http://127.0.0.1:23456/voice?text=text&id这样才是正确的
或者是
http://127.0.0.1:23456/
http://127.0.0.1:23456/voice/
http://127.0.0.1:23456/voice/speakers
这些才是能正常访问的路径

**Comment by Artrajz** [comment]
刚才又看了下你这好像都没报Internal Server Error，检查下是不是防火墙端口没放行？

**Comment by joe12801** [comment]
> 刚才又看了下你这好像都没报Internal Server Error，检查下是不是防火墙端口没放行？

加了/之后可以访问了

**Comment by joe12801** [comment]
> 刚才又看了下你这好像都没报Internal Server Error，检查下是不是防火墙端口没放行？

但是外网的，还是不能访问，不知道什么原因

**Comment by Artrajz** [comment]
根据你的截图我怀疑是没有放行23456端口，因为刚刚路径错误应该显示Internal Server Error才对

**Comment by joe12801** [comment]
> 根据你的截图我怀疑是没有放行23456端口，因为刚刚路径错误应该显示Internal Server Error才对

没问题了，搞定了，因为我装了Warp ，我把他关了就可以了
