### ISSUE TITLE
打不开http后端请求

### ISSUE THREAD

**Issue by yoshino2333** [Artrajz/MoeGoe-Simple-API#14]
![QQ截图20230406214635](https://user-images.githubusercontent.com/105909793/230397610-f509c0e7-9350-4657-86c5-753111fc666e.png)

**config.py**

import os
import sys

JSON_AS_ASCII = False
MAX_CONTENT_LENGTH = 5242880

# 端口
PORT = 23457
# 项目的绝对路径
ABS_PATH = os.path.join(os.path.dirname(os.path.realpath(sys.argv[0])))
# 上传文件的临时路径，非必要不要动
UPLOAD_FOLDER = ABS_PATH + "/upload"
# 音频转换的临时缓存路径，非必要不要动
CACHE_PATH = ABS_PATH + "/cache"

'''
vits模型路径填写方法，MODEL_LIST中的每一行是
[ABS_PATH+"/Model/{模型文件夹}/{.pth模型}", ABS_PATH+"/Model/{模型文件夹}/config.json"],
也可以写相对路径或绝对路径，由于windows和linux路径写法不同，用上面的写法或绝对路径最稳妥
示例：
MODEL_LIST = [
    #VITS
    [ABS_PATH+"/Model/Nene_Nanami_Rong_Tang/1374_epochs.pth", ABS_PATH+"/Model/Nene_Nanami_Rong_Tang/config.json"],
    [ABS_PATH+"/Model/Zero_no_tsukaima/1158_epochs.pth", ABS_PATH+"/Model/Zero_no_tsukaima/config.json"],
    [ABS_PATH+"/Model/g/G_953000.pth", ABS_PATH+"/Model/g/config.json"],
    #HuBert-VITS
    [ABS_PATH+"/Model/louise/360_epochs.pth", ABS_PATH+"/Model/louise/config.json", ABS_PATH+"/Model/louise/hubert-soft-0d54a1f4.pt"],
]
'''
# 模型加载列表
MODEL_LIST = [
    [ABS_PATH+"/Model/g/1374_epochs.pth", ABS_PATH+"/Model/g/config.json"],
]

**docker-compose.yaml**

version: '3.4'
services:
  moegoe:
    image: artrajz/moegoe-simple-api:latest
    restart: always
    ports:
      - 23457:23457
    environment:
      LANG: 'C.UTF-8'
    volumes:
      - ./Model:/app/Model # 挂载模型文件夹
      - ./config.py:/app/config.py # 挂载配置文件

这是模型存放的位置
![QQ截图20230406215335](https://user-images.githubusercontent.com/105909793/230399219-e41c18a1-c876-4bdf-9fcf-3fd30b0cdeab.png)
是哪出问题了呢？

**Comment by Artrajz** [comment]
可以看一下后台日志吗

**Comment by Artrajz** [comment]
尝试复现了出了这个错误，原因是你的模型和config.json是不匹配的，就会出现这个错误，一定要使用该模型对应的config.json

**Comment by yoshino2333** [comment]
已解决，config.json确实不对应，谢谢作者的解答
