### ISSUE TITLE
在docker执行python app.py时出现报错

### ISSUE THREAD

**Issue by AILANTEL** [Artrajz/MoeGoe-Simple-API#5]
文件结构已经检查：
![}L6@(MIT L_O{ 4K{I6)H}B](https://user-images.githubusercontent.com/95335008/229603838-bdded1be-aa57-4381-a9a7-2cb6a06103d3.png)
配置文件已经检查:
![Y 4_X@` %`U6~)F0Y8OH$G9](https://user-images.githubusercontent.com/95335008/229603936-f5a18b63-9bf9-427d-a8ef-7523352cce27.png)
报错截图如下：
![HG7AU$%PI23F`2ED(@_MR{Q](https://user-images.githubusercontent.com/95335008/229603979-c1701781-b6c6-4cfe-9b4c-23f8f67edb3f.png)

**Comment by AILANTEL** [comment]
操作系统:windows 11
使用WSL2搭建docker与linux虚拟机

**Comment by Artrajz** [comment]
`ABS_PATH = os.path.join(os.path.dirname(os.path.realpath(sys.argv[0])))`
改成
`ABS_PATH = os.path.dirname(os.path.realpath(sys.argv[0]))`
试试可以吗，如果不行就暂时直接填绝对路径

**Comment by Artrajz** [comment]
你的路径填错了，要么填绝对路径，要么填ABS_PATH+从Model开始的路径，你可以参考上面的示例
