### ISSUE TITLE
sovits 4.0的模型无法使用

### ISSUE THREAD

**Issue by xiaobaozi233** [Artrajz/MoeGoe-Simple-API#6]
好像是配置文件不兼容导致的，请问有啥解决办法么？

我将配置文件里的"n_speakers"挪到了data里可以正常运行，但是生成wav过程中报错了 ，生成的都是1kb无法播放的文件。

**Comment by Artrajz** [comment]
moegoe项目中本身就没有兼容sovits，而且sovits是适用于声线转换的模型，所以不兼容也是正常的

**Comment by xiaobaozi233** [comment]
理解，我找找转换的工具吧。

**Comment by GTian28** [comment]
> 理解，我找找转换的工具吧。

兄弟有什么转换工具吗？或者如果想训练moegoe项目可用的语音模型，有教程或者链接吗

**Comment by Artrajz** [comment]
> > 理解，我找找转换的工具吧。
> 
> 兄弟有什么转换工具吗？或者如果想训练moegoe项目可用的语音模型，有教程或者链接吗

可以看看vits-finetuning

**Comment by GTian28** [comment]
> > > 理解，我找找转换的工具吧。
> > 
> > 
> > 兄弟有什么转换工具吗？或者如果想训练moegoe项目可用的语音模型，有教程或者链接吗
> 
> 可以看看vits-finetuning

好，感谢
