### ISSUE TITLE
在移动平台重新搭建时出现故障

### ISSUE THREAD

**Issue by AILANTEL** [Artrajz/MoeGoe-Simple-API#7]
平台 win11 WSL2.0 ubuntu
docker能够运行，但是无法输出内容，已经检查模型文件与路径并重新尝试拉取模型三次部署，皆无法解决问题。
输出内容：
![25WQ2L)WMP)`9DTK8`8W`2R](https://user-images.githubusercontent.com/95335008/229728096-bb3db031-d13d-4f8b-93ef-c065e3ec48ad.png)
docker控制台内容:
![%3IOE7_G6H(901(MANW_R`I](https://user-images.githubusercontent.com/95335008/229728148-d1e0c15b-d18a-40d9-bc82-0782f5bf666a.png)
配置文件写法:
![LF1H)XD_ZF)1$9FK8G(PU{1](https://user-images.githubusercontent.com/95335008/229728236-4a3b6854-75d6-497b-bb89-f65655d00436.png)

**Comment by AILANTEL** [comment]
另附上模型文件存放目录，模型文件从该地址下载:https://github.com/CjangCjengh/TTSModels
![A34S1U7UC88LOF`SA7M(MAP](https://user-images.githubusercontent.com/95335008/229728517-ae463a01-12fe-4f96-8518-8157873c8f0a.png)

**Comment by Artrajz** [comment]
从响应结果来看是正常的，你确定没有返回任何结果吗？（结果并不是在后台输出的，而是在发出post的客户端）
请问其他功能正常吗？

**Comment by AILANTEL** [comment]
![QD)GYFCWHI7MNXQ8EV_R)_Q](https://user-images.githubusercontent.com/95335008/229740186-9b4683fe-c36c-4ea7-b99d-028f08175980.png)
经过检查，交互时并未生成语音文件，同时返回：不存在该语音音色。

**Comment by AILANTEL** [comment]
其余功能一切正常，能正常使用文字服务

**Comment by Artrajz** [comment]
这个是机器人那边的服务，你可以先直接测试语音api是否正常，比如在浏览器输入http://ip:端口/voice/speakers
除了转换silk会产生临时文件外，其他格式是直接输出音频文件而不产生临时文件的

**Comment by AILANTEL** [comment]
好的，正在按要求测试

**Comment by Artrajz** [comment]
另外我今天更新了返回的映射表结构，可能这个原因使得chat-gpt-qq原有的读取映射表方式失效

**Comment by AILANTEL** [comment]
![YMI8D1YF$1Y)N2{OMS52( F](https://user-images.githubusercontent.com/95335008/229742163-340ea3ed-ddd9-4457-9e7e-a1e2579e9fed.png)
是的，你的猜测完全没错，服务在正确运行，我会向机器人项目反馈问题，感谢你的耐心。
