### ISSUE TITLE
报错TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by CiaLion** [Artrajz/MoeGoe-Simple-API#9]
按步骤部署最后python app.py时报错
Traceback (most recent call last):
  File "app.py", line 10, in <module>
    from utils import clean_folder, merge_model
  File "C:\Users\Administrator\Desktop\MoeGoe-Simple-API\utils.py", line 120, in <module>
    def to_pcm(in_path: str) -> tuple[str, int]:
TypeError: 'type' object is not subscriptable

**Comment by Artrajz** [comment]
请问你是用什么方式部署的，如果是直接部署，你使用的python版本是？

**Comment by Artrajz** [comment]
抱歉我没有说明，请升级python版本至3.9以上，后续我会在文档里标注python版本的

**Comment by CiaLion** [comment]
> 

好的，感谢
